# Generated by Django 5.2 on 2025-04-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={
                "ordering": ["name"],
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationpermissions",
            options={
                "ordering": ["application", "user_type"],
                "verbose_name": "Application Permission",
                "verbose_name_plural": "Application Permissions",
            },
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profile", "verbose_name_plural": "Profiles"},
        ),
        migrations.AlterModelOptions(
            name="usertype",
            options={
                "ordering": ["name"],
                "verbose_name": "User Type",
                "verbose_name_plural": "User Types",
            },
        ),
    ]
