# Generated by Django 5.2 on 2025-04-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adconnection",
            options={
                "ordering": ["address"],
                "verbose_name": "AD Connection",
                "verbose_name_plural": "AD Connections",
            },
        ),
        migrations.AlterModelOptions(
            name="connection",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Connection",
                "verbose_name_plural": "Connections",
            },
        ),
        migrations.AlterModelOptions(
            name="provider",
            options={
                "ordering": ["name"],
                "verbose_name": "Provider",
                "verbose_name_plural": "Providers",
            },
        ),
        migrations.AddField(
            model_name="adconnection",
            name="ldap_base_dn",
            field=models.CharField(default="DC=example,DC=com,DC=br", max_length=250),
        ),
        migrations.AlterField(
            model_name="adconnection",
            name="address",
            field=models.CharField(default="ldap://0.0.0.0:389", max_length=150),
        ),
        migrations.AlterField(
            model_name="adconnection",
            name="bind_dn",
            field=models.CharField(
                blank=True,
                default="CN=admin,OU=subgrupo,OU=grupo,DC=example,DC=com,DC=br",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="adconnection",
            name="bind_password",
            field=models.CharField(blank=True, default="", max_length=150, null=True),
        ),
    ]
